"""Ajout first_name et last_name à User

Revision ID: 441838fd301c
Revises: 
Create Date: 2025-06-30 16:34:20.459309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441838fd301c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
